language: python
python:
  #- "2.6"
  - "2.7"
  - "3.3"
  #- "3.4"
  - "3.5"
  #- "pypy"
  #- "pypy3"
install:
  - pip install .
  - pip install cson
  - pip install PyYAML
  - pip install codecov
script: coverage run --source biconfigs -m py.test
after_success:
  - codecov
